num_gpus: 0
num_nodes: 1

lr: 0.001
seed: 1
if_cuda: False
gamma: 0.5
log_dir: 'logs'
train_batch: 1
val_batch: 1
test_batch: 1
num_workers: 8
model_name: 'test1'
lr_schedule: [20, 50, 100, 300]
epochs: 2
train_dir: "../data/Schlieren/train/"
val_dir: "../data/Schlieren/val/"
test_dir: "../data/Schlieren/test/"
pred_dir: "../data/Schlieren/pred/"
out_dir: "results"
start: 0.0
stop: 5.0
step: 0.1
height: [74, 748]
width: [258, 692]
